Firs bot version
ilb/deepfaq pull request #3
Opened 2021-02-17 08:11 UTC by kvadro1

Первая версия бота.
В папке lib библиотека deeppavlov_faq_bot непосредственно работающая с deepapvlov, её надо установить до запуска сервиса. Библиотека при добавлении данных в несуществующую ещё модель создаёт файловую структуру для модели и обучает новую модель,в случае существования модели происходит добавление данных и обучение модели с новыми данными.

2021-02-19 18:32 UTC, MaximumQuiet commented
Посмотрел, запустил бота, добавление вопросов, ответов / ответы на вопросы работает

Что лучше исправить (по проекту):
1. Объединить library и app в одно целое. Здесь была моя ошибка, т.к. шаблон репозитория содержит шаблон библиотеки и шаблон веб-приложения сразу. В этом случае достаточно, чтобы весь код приложения был единым проектом и устанавливался как одно целое.
2. Также нужно избавиться от anaconda (environment.yml файлов)
3. Добавить расширение .pyc в .gitignore, т.к. это просто питоновский кэш
4. Я вижу ты описал API в openapi.yaml - к проекту можно подключить интерфейс для просмотра и выполнения тестовых запросов через вот эту любу https://github.com/cope-systems/bottle-swagger. Она позволяет его подключить через bottle.install(), как плагин. Рекомендуемые параметры - validate_swagger_spec=False, serve_swagger_ui=True, swagger_ui_suburl=/swagger/, остальные можно не ставить.

2021-02-19 18:33 UTC, MaximumQuiet commented on app/webapp/services/addservice.py
> +class AddDataService:
Как я понимаю классы AddDataService и AnswerService это варианты использования? Тогда лучше будет их обозвать как-то вроде AddTrainData, GetAnswer

2021-02-19 18:33 UTC, MaximumQuiet commented on app/webapp/services/answerservice.py
> +        bot = faqbot.FaqBot(self.work_dir)
Вместо того, чтобы каждый раз инициализировать FaqBot, предлагаю создать его в конфиге один раз, а потом использовать как зависимость в AddTrainData и GetAnswer

2021-02-23 06:29 UTC, kvadro1 commented
Вроде всё поправил

2021-02-23 18:27 UTC, MaximumQuiet requested changes

2021-02-23 18:27 UTC, MaximumQuiet commented on app/webapp/config/config.py
> +    binder.bind(GetAnswer, GetAnswer(bot))
Да, ещё забыл упомянуть в первом комментарии - у библиотеки inject реализовано создание объектов в рантайме. То есть объекты, которые не требуют сложной конфигурации (например классы GetAnswer, AddTrainData) можно вообще не объявлять через binder.bind. Достаточно просто объявить FaqBot, а GetAnswer и AddTrainData создадутся сами и используют уже имеющийся FaqBot в контейнере.

2021-02-23 18:28 UTC, MaximumQuiet commented
В принципе ты всё исправил, только нужно ещё вынести содержимое папки app в корень, т.к. это и есть корень проекта

2021-02-24 06:06 UTC, MaximumQuiet approved these changes
@slavb18 у меня пока больше замечаний нет

2021-02-25 03:25 UTC, slavb18 commented
Сейчас оба сервиса реализованы - обучение и получение ответов?

2021-03-01 07:53 UTC, merged